const MEMBERS = [
  {
    id: 1,
    year: 4,
    nickname: "니니",
    name: "김유빈",
    part: "IOS",
    position: "회장",
    github: "ubeeni",
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 2,
    year: 4,
    nickname: "케빈",
    name: "김근식",
    part: "SPRING",
    position: "부회장",
    github: "600gramSik",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 3,
    year: 4,
    nickname: "해누",
    name: "김현우",
    part: "SPRING",
    position: "부회장",
    github: "khw18",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 4,
    year: 4,
    nickname: "원스",
    name: "김유정",
    part: "ANDROID",
    position: "파트장",
    github: "newoldname",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 5,
    year: 4,
    nickname: "폴",
    name: "김필규",
    part: "IOS",
    position: "파트장",
    github: "pingu00",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 6,
    year: 4,
    nickname: "포디",
    name: "정서현",
    part: "WEB",
    position: "파트장",
    github: "JSH99",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 7,
    year: 4,
    nickname: "동키",
    name: "김동현",
    part: "SPRING",
    position: "파트장",
    github: "DDonghyeo",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 8,
    year: 4,
    nickname: "민팍",
    name: "박민희",
    part: "NODE",
    position: "파트장",
    github: "himinsunsine",
    sex: "w",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 9,
    year: 4,
    nickname: "검정",
    name: "권혁찬",
    part: "ANDROID",
    position: "챌린저",
    github: "kwon-h-chan",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 10,
    year: 4,
    nickname: "코코",
    name: "최진규",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 11,
    year: 4,
    nickname: "주니",
    name: "김영준",
    part: "IOS",
    position: "챌린저",
    github: "Yjooon",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 12,
    year: 4,
    nickname: "스히",
    name: "백서희",
    part: "IOS",
    position: "챌린저",
    github: "soycong",
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 13,
    year: 4,
    nickname: "딩동",
    name: "이동현",
    part: "IOS",
    position: "챌린저",
    github: "taipaise",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 14,
    year: 4,
    nickname: "지토",
    name: "이현호",
    part: "IOS",
    position: "챌린저",
    github: "LeeHyeonHo-127",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 15,
    year: 4,
    nickname: "피딕",
    name: "황인성",
    part: "IOS",
    position: "챌린저",
    github: "Fiddich-Dev",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 16,
    year: 4,
    nickname: "린니",
    name: "이혜린",
    part: "WEB",
    position: "챌린저",
    github: "HYERINI",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 17,
    year: 4,
    nickname: "아마다",
    name: "조재석",
    part: "WEB",
    position: "챌린저",
    github: "Pridesd",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 18,
    year: 4,
    nickname: "제이",
    name: "김영재",
    part: "WEB",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 19,
    year: 4,
    nickname: "데이빗",
    name: "김태영",
    part: "WEB",
    position: "챌린저",
    github: "kimdavid0521",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 20,
    year: 4,
    nickname: "우비",
    name: "박원우",
    part: "WEB",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 21,
    year: 4,
    nickname: "매튜",
    name: "김용민",
    part: "WEB",
    position: "챌린저",
    github: "dydals3440",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 22,
    year: 4,
    nickname: "지구",
    name: "안지수",
    part: "WEB",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 23,
    year: 4,
    nickname: "제이미",
    name: "김준환",
    part: "SPRING",
    position: "챌린저",
    github: "catturtle123",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 24,
    year: 4,
    nickname: "디채",
    name: "김채연",
    part: "SPRING",
    position: "챌린저",
    github: "yeon-22k",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 25,
    year: 4,
    nickname: "제이스",
    name: "임재영",
    part: "SPRING",
    position: "챌린저",
    github: "limjustin",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 26,
    year: 4,
    nickname: "사하",
    name: "윤근수",
    part: "SPRING",
    position: "챌린저",
    github: "rlJzr",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 27,
    year: 4,
    nickname: "링키",
    name: "윤수빈",
    part: "SPRING",
    position: "챌린저",
    github: "soogoori",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 28,
    year: 4,
    nickname: "하비",
    name: "이승주",
    part: "SPRING",
    position: "챌린저",
    github: "WinsomeJoo",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 29,
    year: 4,
    nickname: "블루",
    name: "최민주",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 30,
    year: 4,
    nickname: "윤",
    name: "권오윤",
    part: "SPRING",
    position: "챌린저",
    github: "k-oyun",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 31,
    year: 4,
    nickname: "세헌",
    name: "호세헌",
    part: "SPRING",
    position: "챌린저",
    github: "seheonnn",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 32,
    year: 4,
    nickname: "한뉴",
    name: "한유성",
    part: "SPRING",
    position: "챌린저",
    github: "tkamo2006",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 33,
    year: 4,
    nickname: "우현",
    name: "이현우",
    part: "SPRING",
    position: "챌린저",
    github: "HyunwooYi",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 34,
    year: 4,
    nickname: "이네",
    name: "설인혜",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 35,
    year: 4,
    nickname: "쫑",
    name: "김종한",
    part: "NODE",
    position: "챌린저",
    github: "entere77",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 36,
    year: 4,
    nickname: "뻔뻔",
    name: "김건",
    part: "NODE",
    position: "챌린저",
    github: "funfungun",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 37,
    year: 4,
    nickname: "예닝",
    name: "문예윤",
    part: "NODE",
    position: "챌린저",
    github: "moonyaeyoon",
    sex: "w",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 38,
    year: 4,
    nickname: "하나빈",
    name: "이원빈",
    part: "NODE",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 39,
    year: 4,
    nickname: "엘레나",
    name: "권유정",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 40,
    year: 4,
    nickname: "디아",
    name: "전지민",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 41,
    year: 4,
    nickname: "깐",
    name: "김가은",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 42,
    year: 4,
    nickname: "덕구",
    name: "이다슬",
    part: "PLAN",
    position: "챌린저",
    github: "dasrizzang",
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 43,
    year: 4,
    nickname: "와제",
    name: "정여진",
    part: "PLAN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 44,
    year: 2,
    nickname: "루피",
    name: "강세미",
    part: "SPRING",
    position: "회장",
    github: "semi-cloud",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 45,
    year: 2,
    nickname: "민니",
    name: "임지민",
    part: "SPRING",
    position: "부회장",
    github: "jimin3263",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 46,
    year: 2,
    nickname: "마크",
    name: "이기탁",
    part: "SPRING",
    position: "파트장",
    github: "gitak",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 47,
    year: 2,
    nickname: "로아",
    name: "김성은",
    part: "WEB",
    position: "파트장",
    github: "FEKimseongeun",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 48,
    year: 2,
    nickname: "빙수",
    name: "박민수",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 49,
    year: 2,
    nickname: "클라인",
    name: "최승호",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 50,
    year: 2,
    nickname: "뿅뿅",
    name: "김부용",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 51,
    year: 2,
    nickname: "솔솔",
    name: "이한솔",
    part: "ANDROID",
    position: "챌린저",
    github: "EstherHansol",
    sex: "w",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 52,
    year: 2,
    nickname: "추리",
    name: "김연출",
    part: "ANDROID",
    position: "챌린저",
    github: "kimyeonchul",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 53,
    year: 2,
    nickname: "해누",
    name: "김현우",
    part: "ANDROID",
    position: "챌린저",
    github: "khw18",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 54,
    year: 2,
    nickname: "조이",
    name: "황선웅",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 55,
    year: 2,
    nickname: "셩",
    name: "양서영",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 56,
    year: 2,
    nickname: "쿼카",
    name: "박채린",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 57,
    year: 2,
    nickname: "구름",
    name: "서성민",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 58,
    year: 2,
    nickname: "하나",
    name: "최가나",
    part: "SPRING",
    position: "챌린저",
    github: "choign3123",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 59,
    year: 2,
    nickname: "수",
    name: "정연수",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 60,
    year: 2,
    nickname: "벨라",
    name: "박건호",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 61,
    year: 2,
    nickname: "매실",
    name: "김현재",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 62,
    year: 2,
    nickname: "환",
    name: "이환수",
    part: "SPRING",
    position: "챌린저",
    github: "Lee-hwansoo",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 63,
    year: 2,
    nickname: "퍼플",
    name: "김동욱",
    part: "SPRING",
    position: "챌린저",
    github: "DongwookKim0823",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 64,
    year: 2,
    nickname: "스노우",
    name: "김지연",
    part: "NODE",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 65,
    year: 2,
    nickname: "쿠로미",
    name: "조예진",
    part: "NODE",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 66,
    year: 2,
    nickname: "제트",
    name: "김진석",
    part: "NODE",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 67,
    year: 2,
    nickname: "무너",
    name: "문정호",
    part: "IOS",
    position: "챌린저",
    github: "ILWAT",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 68,
    year: 2,
    nickname: "니니",
    name: "김유빈",
    part: "IOS",
    position: "챌린저",
    github: "ubeeni",
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 69,
    year: 2,
    nickname: "추추",
    name: "추희승",
    part: "WEB",
    position: "챌린저",
    github: "chuheeseung",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 70,
    year: 2,
    nickname: "포디",
    name: "정서현",
    part: "WEB",
    position: "챌린저",
    github: "JSH99",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 71,
    year: 3,
    nickname: "솔솔",
    name: "이한솔",
    part: "SPRING",
    position: "회장",
    github: "EstherHansol",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 72,
    year: 3,
    nickname: "무너",
    name: "문정호",
    part: "IOS",
    position: "부회장",
    github: "ILWAT",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 73,
    year: 3,
    nickname: "앨리",
    name: "양서영",
    part: "ANDROID",
    position: "부회장",
    github: null,
    sex: "w",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 74,
    year: 3,
    nickname: "환",
    name: "이환수",
    part: "ANDROID",
    position: "파트장",
    github: "Lee-hwansoo",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 75,
    year: 3,
    nickname: "니니",
    name: "김유빈",
    part: "IOS",
    position: "파트장",
    github: "ubeeni",
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 76,
    year: 3,
    nickname: "퍼플",
    name: "김동욱",
    part: "SPRING",
    position: "파트장",
    github: "DongwookKim0823",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 77,
    year: 3,
    nickname: "포디",
    name: "정서현",
    part: "NODE",
    position: "파트장",
    github: "JSH99",
    sex: "w",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 78,
    year: 3,
    nickname: "마크",
    name: "이기탁",
    part: "SPRING",
    position: "파트장",
    github: "gitak",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 79,
    year: 3,
    nickname: "레이",
    name: "윤채영",
    part: "IOS",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 80,
    year: 3,
    nickname: "다우니",
    name: "최다경",
    part: "IOS",
    position: "챌린저",
    github: "ekrud99",
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 81,
    year: 3,
    nickname: "폴",
    name: "김필규",
    part: "IOS",
    position: "챌린저",
    github: "pingu00",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 82,
    year: 3,
    nickname: "피딕",
    name: "황인성",
    part: "IOS",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 83,
    year: 3,
    nickname: "하이준",
    name: "안영준",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 84,
    year: 3,
    nickname: "원스",
    name: "김유정",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 85,
    year: 3,
    nickname: "데니",
    name: "유상민",
    part: "ANDROID",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 86,
    year: 3,
    nickname: "올리버",
    name: "최현민",
    part: "SPRING",
    position: "챌린저",
    github: "hyunmin0317",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 87,
    year: 3,
    nickname: "해누",
    name: "김현우",
    part: "SPRING",
    position: "챌린저",
    github: "khw18",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 88,
    year: 3,
    nickname: "동키",
    name: "김동현",
    part: "SPRING",
    position: "챌린저",
    github: "DDonghyeo",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 89,
    year: 3,
    nickname: "케빈",
    name: "김근식",
    part: "SPRING",
    position: "챌린저",
    github: "600gramSik",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 90,
    year: 3,
    nickname: "비버닉",
    name: "양원준",
    part: "SPRING",
    position: "챌린저",
    github: "ywj9811",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 91,
    year: 3,
    nickname: "그린",
    name: "김유민",
    part: "SPRING",
    position: "챌린저",
    github: "minyou2675",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 92,
    year: 3,
    nickname: "세헌",
    name: "호세헌",
    part: "SPRING",
    position: "챌린저",
    github: "seheonnn",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 93,
    year: 3,
    nickname: "하비",
    name: "이승주",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 94,
    year: 3,
    nickname: "포트",
    name: "조현준",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 95,
    year: 3,
    nickname: "민팍",
    name: "박민희",
    part: "NODE",
    position: "챌린저",
    github: "himinsunsine",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 96,
    year: 3,
    nickname: "쫑",
    name: "김종한",
    part: "NODE",
    position: "챌린저",
    github: "entere77",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 97,
    year: 3,
    nickname: "주니",
    name: "김형준",
    part: "NODE",
    position: "챌린저",
    github: "hyoungj00n",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 98,
    year: 5,
    nickname: "데이빗",
    name: "김태영",
    part: "WEB",
    position: "회장",
    github: "kimdavid0521",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 99,
    year: 5,
    nickname: "니니",
    name: "김유빈",
    part: "IOS",
    position: "부회장",
    github: "ubeeni",
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 100,
    year: 5,
    nickname: "검정",
    name: "권혁찬",
    part: "ANDROID",
    position: "파트장",
    github: "kwon-h-chan",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 101,
    year: 5,
    nickname: "피딕",
    name: "황인성",
    part: "IOS",
    position: "파트장",
    github: "Fiddich-Dev",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 102,
    year: 5,
    nickname: "매튜",
    name: "김용민",
    part: "WEB",
    position: "파트장",
    github: "dydals3440",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 103,
    year: 5,
    nickname: "제이스",
    name: "임재영",
    part: "SPRING",
    position: "파트장",
    github: "limjustin",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 104,
    year: 5,
    nickname: "예닝",
    name: "문예윤",
    part: "NODE",
    position: "파트장",
    github: "moonyaeyoon",
    sex: "w",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 105,
    year: 5,
    nickname: "깐",
    name: "김가은",
    part: "DESIGN",
    position: "파트장",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 106,
    year: 5,
    nickname: "덕구",
    name: "이다슬",
    part: "PLAN",
    position: "파트장",
    github: "dasrizzang",
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 107,
    year: 5,
    nickname: "다에몬",
    name: "정승원",
    part: "ANDROID",
    position: "챌린저",
    github: "tristanjung1006",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 108,
    year: 5,
    nickname: "러츠",
    name: "강다희",
    part: "ANDROID",
    position: "챌린저",
    github: "daheebb",
    sex: "w",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 109,
    year: 5,
    nickname: "마린",
    name: "강바다",
    part: "ANDROID",
    position: "챌린저",
    github: "202111255",
    sex: "w",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 110,
    year: 5,
    nickname: "딩동",
    name: "이동현",
    part: "IOS",
    position: "챌린저",
    github: "taipaise",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 111,
    year: 5,
    nickname: "도요",
    name: "김영준",
    part: "IOS",
    position: "챌린저",
    github: "Yjooon",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 112,
    year: 5,
    nickname: "지토",
    name: "이현호",
    part: "IOS",
    position: "챌린저",
    github: "LeeHyeonHo-127",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 113,
    year: 5,
    nickname: "데브",
    name: "이지민",
    part: "WEB",
    position: "챌린저",
    github: "201910825",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 114,
    year: 5,
    nickname: "다라",
    name: "차다인",
    part: "WEB",
    position: "챌린저",
    github: "daindaind",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 115,
    year: 5,
    nickname: "시로",
    name: "박선균",
    part: "WEB",
    position: "챌린저",
    github: "qkrtjsrbs315",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 116,
    year: 5,
    nickname: "레이튼",
    name: "박지환",
    part: "WEB",
    position: "챌린저",
    github: "zihwanpack",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 117,
    year: 5,
    nickname: "도톨이",
    name: "하지수",
    part: "WEB",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 118,
    year: 5,
    nickname: "세헌",
    name: "호세헌",
    part: "SPRING",
    position: "챌린저",
    github: "seheonnn",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 119,
    year: 5,
    nickname: "우현",
    name: "이현우",
    part: "SPRING",
    position: "챌린저",
    github: "HyunwooYi",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 120,
    year: 5,
    nickname: "제이미",
    name: "김준환",
    part: "SPRING",
    position: "챌린저",
    github: "catturtle123",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 121,
    year: 5,
    nickname: "사하",
    name: "윤근수",
    part: "SPRING",
    position: "챌린저",
    github: "rlJzr",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 122,
    year: 5,
    nickname: "하나",
    name: "최가나",
    part: "SPRING",
    position: "챌린저",
    github: "choign3123",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 123,
    year: 5,
    nickname: "주니",
    name: "김형준",
    part: "SPRING",
    position: "챌린저",
    github: "hyoungj00n",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 124,
    year: 5,
    nickname: "구리",
    name: "박상우",
    part: "SPRING",
    position: "챌린저",
    github: "pswoo0323",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 125,
    year: 5,
    nickname: "렉스",
    name: "변성호",
    part: "SPRING",
    position: "챌린저",
    github: "Byun-Sung-Ho",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 126,
    year: 5,
    nickname: "요비",
    name: "김승엽",
    part: "SPRING",
    position: "챌린저",
    github: "yeopyeop-82",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 127,
    year: 5,
    nickname: "주디",
    name: "이연주",
    part: "SPRING",
    position: "챌린저",
    github: "Lee-Yeonjoo",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 128,
    year: 5,
    nickname: "뻔뻔",
    name: "김건",
    part: "NODE",
    position: "챌린저",
    github: "funfungun",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 129,
    year: 5,
    nickname: "냥젤리",
    name: "김훈",
    part: "NODE",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 130,
    year: 5,
    nickname: "하늘",
    name: "강호준",
    part: "NODE",
    position: "챌린저",
    github: "LunarStella",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 131,
    year: 5,
    nickname: "엘레나",
    name: "권유정",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 132,
    year: 5,
    nickname: "파스텔",
    name: "정서연",
    part: "DESIGN",
    position: "챌린저",
    github: "seoyeon0327",
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 133,
    year: 5,
    nickname: "가니",
    name: "박가은",
    part: "PLAN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 134,
    year: 5,
    nickname: "라일락",
    name: "정서영",
    part: "PLAN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 135,
    year: 5,
    nickname: "루시퍼",
    name: "박세현",
    part: "PLAN",
    position: "챌린저",
    github: "ParkSeHyun-github",
    sex: "m",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 137,
    year: 5,
    nickname: "요비",
    name: "김승엽",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 138,
    year: 5,
    nickname: "주디",
    name: "이연주",
    part: "SPRING",
    position: "챌린저",
    github: "Lee-Yeonjoo",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 139,
    year: 5,
    nickname: "뻔뻔",
    name: "김건",
    part: "NODE",
    position: "챌린저",
    github: "funfungun",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 140,
    year: 5,
    nickname: "냥젤리",
    name: "김훈",
    part: "NODE",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 141,
    year: 5,
    nickname: "하늘",
    name: "강호준",
    part: "NODE",
    position: "챌린저",
    github: "LunarStella",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 142,
    year: 5,
    nickname: "엘레나",
    name: "권유정",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 143,
    year: 5,
    nickname: "파스텔",
    name: "정서연",
    part: "DESIGN",
    position: "챌린저",
    github: "seoyeon0327",
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 144,
    year: 5,
    nickname: "가니",
    name: "박가은",
    part: "PLAN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 145,
    year: 5,
    nickname: "라일락",
    name: "정서영",
    part: "PLAN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 146,
    year: 5,
    nickname: "루시퍼",
    name: "박세현",
    part: "PLAN",
    position: "챌린저",
    github: "ParkSeHyun-github",
    sex: "m",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 147,
    year: 6,
    nickname: "매튜",
    name: "김용민",
    part: "WEB",
    position: "회장",
    github: "dydals3440",
    sex: "m",
    project: null,
    skill: ["JS", "React", "Next", "Node", "Nest", "React Native"],
  },
  {
    id: 148,
    year: 6,
    nickname: "다라",
    name: "차다인",
    part: "WEB",
    position: "부회장",
    github: "daindaind",
    sex: "w",
    project: null,
    skill: ["JS", "React", "Next", "Node", "RN"],
  },
  {
    id: 149,
    year: 6,
    nickname: "조이",
    name: "정혜원",
    part: "WEB",
    position: "챌린저",
    github: "hijjoy",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 150,
    year: 6,
    nickname: "유니",
    name: "이혜윤",
    part: "WEB",
    position: "챌린저",
    github: "hyeyoon23",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 151,
    year: 6,
    nickname: "노먼",
    name: "이찬민",
    part: "WEB",
    position: "챌린저",
    github: "dlcksals87",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 152,
    year: 6,
    nickname: "뻔뻔",
    name: "김건",
    part: "WEB",
    position: "챌린저",
    github: "alpha5179",
    sex: "m",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 153,
    year: 6,
    nickname: "히연",
    name: "김희연",
    part: "WEB",
    position: "챌린저",
    github: "kimhy030927",
    sex: "w",
    project: null,
    skill: ["HTML", "CSS", "JS", "React"],
  },
  {
    id: 154,
    year: 6,
    nickname: "주니",
    name: "김형준",
    part: "NODE",
    position: "파트장",
    github: null,
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 155,
    year: 6,
    nickname: "시로",
    name: "박선균",
    part: "NODE",
    position: "챌린저",
    github: "qkrtjsrbs315",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 156,
    year: 6,
    nickname: "어니",
    name: "박은희",
    part: "NODE",
    position: "챌린저",
    github: "arongsnuna",
    sex: "w",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 157,
    year: 6,
    nickname: "레이튼",
    name: "박지환",
    part: "NODE",
    position: "챌린저",
    github: "hwan8807",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 158,
    year: 6,
    nickname: "티모",
    name: "정준영",
    part: "NODE",
    position: "챌린저",
    github: "jjy1111202",
    sex: "m",
    project: null,
    skill: ["JS", "Node"],
  },
  {
    id: 159,
    year: 6,
    nickname: "다에몬",
    name: "정승원",
    part: "ANDROID",
    position: "파트장",
    github: null,
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 160,
    year: 6,
    nickname: "페리오",
    name: "박태정",
    part: "ANDROID",
    position: "챌린저",
    github: "taejung2mail",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 161,
    year: 6,
    nickname: "비니",
    name: "홍다빈",
    part: "ANDROID",
    position: "챌린저",
    github: "ghdekqls821",
    sex: "w",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 162,
    year: 6,
    nickname: "세레나",
    name: "정서현",
    part: "ANDROID",
    position: "챌린저",
    github: "tjgusid",
    sex: "w",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 163,
    year: 6,
    nickname: "냥젤리",
    name: "김훈",
    part: "ANDROID",
    position: "챌린저",
    github: "tonyk0521",
    sex: "m",
    project: null,
    skill: ["Kotlin"],
  },
  {
    id: 164,
    year: 6,
    nickname: "허프만",
    name: "임진영",
    part: "IOS",
    position: "챌린저",
    github: "jinyoungim105",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 165,
    year: 6,
    nickname: "푸린",
    name: "김민지",
    part: "IOS",
    position: "챌린저",
    github: "vivi020405",
    sex: "w",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 166,
    year: 6,
    nickname: "도화",
    name: "문정현",
    part: "IOS",
    position: "챌린저",
    github: "daniel101115",
    sex: "m",
    project: null,
    skill: ["Swift"],
  },
  {
    id: 167,
    year: 6,
    nickname: "가니",
    name: "박가은",
    part: "PM",
    position: "파트장",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 168,
    year: 6,
    nickname: "제리",
    name: "김태영",
    part: "PM",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 169,
    year: 6,
    nickname: "닉드",
    name: "임수현",
    part: "PM",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 170,
    year: 6,
    nickname: "루나",
    name: "조희선",
    part: "PM",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 171,
    year: 6,
    nickname: "엘레나",
    name: "권유정",
    part: "DESIGN",
    position: "파트장",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 172,
    year: 6,
    nickname: "세리",
    name: "김세연",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 173,
    year: 6,
    nickname: "으니",
    name: "정은희",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 174,
    year: 6,
    nickname: "헤일린",
    name: "구현희",
    part: "DESIGN",
    position: "챌린저",
    github: null,
    sex: "w",
    project: null,
    skill: ["Figma"],
  },
  {
    id: 175,
    year: 6,
    nickname: "제이미",
    name: "김준환",
    part: "SPRING",
    position: "파트장",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 176,
    year: 6,
    nickname: "우현",
    name: "이현우",
    part: "SPRING",
    position: "챌린저",
    github: "stephenyi28",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 177,
    year: 6,
    nickname: "챔챔",
    name: "김채민",
    part: "SPRING",
    position: "챌린저",
    github: "alslalsl3125",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 178,
    year: 6,
    nickname: "리키",
    name: "김진호",
    part: "SPRING",
    position: "챌린저",
    github: null,
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 179,
    year: 6,
    nickname: "도널드",
    name: "김종우",
    part: "SPRING",
    position: "챌린저",
    github: "kijiwi1",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 180,
    year: 6,
    nickname: "요시",
    name: "서정모",
    part: "SPRING",
    position: "챌린저",
    github: "wjdah1402",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 181,
    year: 6,
    nickname: "테드",
    name: "고민영",
    part: "SPRING",
    position: "챌린저",
    github: "gomin0981113",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 182,
    year: 6,
    nickname: "주디",
    name: "박세은",
    part: "SPRING",
    position: "챌린저",
    github: "eum7548920",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 183,
    year: 6,
    nickname: "예닝",
    name: "문예윤",
    part: "SPRING",
    position: "챌린저",
    github: "moonyaeyoon",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 184,
    year: 6,
    nickname: "데이빗",
    name: "김태영",
    part: "SPRING",
    position: "챌린저",
    github: "trust00005",
    sex: "m",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 185,
    year: 6,
    nickname: "지니",
    name: "김지민",
    part: "SPRING",
    position: "챌린저",
    github: "kitty14904",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 186,
    year: 6,
    nickname: "카온",
    name: "유채원",
    part: "SPRING",
    position: "챌린저",
    github: "yoocw0426",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
  {
    id: 187,
    year: 6,
    nickname: "마린",
    name: "강바다",
    part: "SPRING",
    position: "챌린저",
    github: "kbd1120",
    sex: "w",
    project: null,
    skill: ["Java", "Spring"],
  },
];

export { MEMBERS };
